using System;

public class DataConsulta3{
    public string name {get; set;}
    public int count {get; set;} 
}

public class DataConsulta4{
    public string nombre {get; set;}
    public int cantidad {get; set;}
}

public class DataConsulta5{
    public string producto {get; set;}
    public decimal cantidad {get; set;}
}

public class DataConsulta6{
    public string producto_codigo {get; set;}
    public string nombre {get; set;}
    public decimal cantidad {get; set;}
}

public class DataConsulta7 {
    public decimal cantidad {get; set;}
}

public class Dataconsulta8{
    public int id {get; set;}
    public string nombre {get; set;}
    public int cantidad {get; set;}
}

public class Dataconsulta9{
    public string nombre {get; set;}
    public int cantidad {get; set;}
}